### ISSUE TITLE
待办事项-pc端发布活动模板

### ISSUE THREAD

**Issue by zhangzhe2017** [zhangzhe2017/zoo#5]
1. 保留手机端所有字段
2. 活动详情使用富文本，可放置样式以及图片
3.  <s>可发布&自定义需要报名者填写的字段。</s>

**Comment by xsjohn0306** [comment]
- 富文本文字大小需要处理一下 已完成, 需要用户手动设置字体大小
- PC端上传需要找一个组件 已完成
